function [figure1,axes1]=WhiteFigureLog(ttl,ylbl,xlbl)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 17-Oct-2012 17:12:26

% Create figure
figure1 = figure('XVisual','','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'ZColor',[0 0 0],'YScale','log',...
    'YMinorTick','on',...
    'YMinorGrid','on',...
    'YColor',[0 0 0],...
    'XColor',[0 0 0],...
    'FontSize',12,...
    'FontName','times',...
    'Color',[1 1 1]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create ylabel
ylabel(ylbl,'FontSize',12,'FontName','times',...
    'Color',[0 0 0]);

% Create xlabel
xlabel(xlbl,'FontSize',12,'FontName','times','Color',[0 0 0]);

% Create title
title(ttl,'FontSize',12,'FontName','times',...
    'Color',[0 0 0]);

